spring.application.name=PrimeiroProjetoSpring
spring.datasource.url=jdbc:mysql://localhost:3306/remedio_api
spring.datasource.username=root
spring.datasource.password=
spring.liquibase.enabled=false
serve.error.inclube-stacktrace=never