spring.application.name=PrimeiroProjetoSpring
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.liquibase.enabled=false
serve.error.inclube-stacktrace=never
api_security.token.secret=${JWT_Secret:123456} 